name: Test dependency PRs
on:
  merge_group:
  push:
    branches:
      - 'dependabot/**'
      - 'update-digests'
      - 'renovate/**'
      - 'feat/**'

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN || github.token }}
    permissions:
      contents: "read"
    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.1

      - name: Setup pnpm
        uses: pnpm/action-setup@v6.0.9

      - name: Setup node
        uses: actions/setup-node@v7.1.0
        with:
          node-version: "26.x"
          cache: "pnpm"
          registry-url: "https://npm.pkg.github.com"

      - name: Cache node_modules
        uses: actions/cache@v6.1.0
        id: node_modules
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install dependencies
        if: steps.node_modules.outputs.cache-hit != 'true'
        run: pnpm install --ignore-scripts

      - name: Run tests
        run: pnpm test
